/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UnUsedPin_10.h"
#include "UnUsedPin_10_aliases.h"
#include "UnUsedPin_18.h"
#include "UnUsedPin_18_aliases.h"
#include "TC_CC_ISR.h"
#include "Clock_1.h"
#include "Timer_1.h"
#include "Pin_Power.h"
#include "Pin_Power_aliases.h"
#include "isr_WDT.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "hawkeye_data.h"
#include "hawkeye_data_aliases.h"
#include "hawkeye_clk.h"
#include "hawkeye_clk_aliases.h"
#include "UnUsedPin_14.h"
#include "UnUsedPin_14_aliases.h"
#include "UnUsedPin_9.h"
#include "UnUsedPin_9_aliases.h"
#include "UnUsedPin_15.h"
#include "UnUsedPin_15_aliases.h"
#include "UnUsedPin_16.h"
#include "UnUsedPin_16_aliases.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "CapSense_SampleClk.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

